INSERT INTO `operator` (`alias`) VALUES ('AWCC');
INSERT INTO `operator` (`alias`) VALUES ('Roshan');
INSERT INTO `operator` (`alias`) VALUES ('New1');
INSERT INTO `operator` (`alias`) VALUES ('Areeba Afghanistan');
INSERT INTO `operator` (`alias`) VALUES ('Afghan Telecom');
INSERT INTO `operator` (`alias`) VALUES ('Albanian Mobile Communications (AMC)');
INSERT INTO `operator` (`alias`) VALUES ('Vodafone Albania');
INSERT INTO `operator` (`alias`) VALUES ('Eagle Mobile');
INSERT INTO `operator` (`alias`) VALUES ('Mobile 4 AL');
INSERT INTO `operator` (`alias`) VALUES ('Algérie Telecom');
INSERT INTO `operator` (`alias`) VALUES ('Orascom Telecom Algérie');
INSERT INTO `operator` (`alias`) VALUES ('Mobiland');
INSERT INTO `operator` (`alias`) VALUES ('Unitel');
INSERT INTO `operator` (`alias`) VALUES ('Movicel');
INSERT INTO `operator` (`alias`) VALUES ('Weblinks Limited');
INSERT INTO `operator` (`alias`) VALUES ('APUA PCS');
INSERT INTO `operator` (`alias`) VALUES ('Cable & Wireless (Antigua)');
INSERT INTO `operator` (`alias`) VALUES ('AT&T Wireless (Antigua)');
INSERT INTO `operator` (`alias`) VALUES ('Compañia de Radiocomunicaciones Moviles S.A.');
INSERT INTO `operator` (`alias`) VALUES ('Nextel Argentina srl');
INSERT INTO `operator` (`alias`) VALUES ('Telefónica Comunicaciones Personales S.A.');
INSERT INTO `operator` (`alias`) VALUES ('CTI PCS S.A.');
INSERT INTO `operator` (`alias`) VALUES ('Compañia de Telefonos del Interior Norte S.A.');
INSERT INTO `operator` (`alias`) VALUES ('Compañía de Telefonos del Interior S.A.');
INSERT INTO `operator` (`alias`) VALUES ('Telecom Personal S.A.');
INSERT INTO `operator` (`alias`) VALUES ('Setar GSM');
INSERT INTO `operator` (`alias`) VALUES ('Telstra Corporation Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('Optus Mobile Pty. Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('Vodafone Network Pty. Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('Department of Defence');
INSERT INTO `operator` (`alias`) VALUES ('The Ozitel Network Pty. Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('Hutchison 3G Australia Pty. Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('Airnet Commercial Australia Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('Norfolk Telecom');
INSERT INTO `operator` (`alias`) VALUES ('Hutchison Telecommunications (Australia) Pty. Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('AAPT Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('3GIS Pty Ltd. (Telstra & Hutchison 3G)');
INSERT INTO `operator` (`alias`) VALUES ('Victorian Rail Track');
INSERT INTO `operator` (`alias`) VALUES ('Vivid Wireless Pty Ltd');
INSERT INTO `operator` (`alias`) VALUES ('Pactel International Pty Ltd');
INSERT INTO `operator` (`alias`) VALUES ('Lycamobile Pty Ltd');
INSERT INTO `operator` (`alias`) VALUES ('Ausgrid Corporation');
INSERT INTO `operator` (`alias`) VALUES ('Queensland Rail Limited');
INSERT INTO `operator` (`alias`) VALUES ('Advanced Communications Technologies Pty. Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('NBNCo Ltd');
INSERT INTO `operator` (`alias`) VALUES ('Localstar Holding Pty. Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('Optus Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('Hutchison 3G Austria GmbH');
INSERT INTO `operator` (`alias`) VALUES ('Barablu Mobile Austria Ltd');
INSERT INTO `operator` (`alias`) VALUES ('Azercell Limited Liability Joint Venture');
INSERT INTO `operator` (`alias`) VALUES ('Catel JV');
INSERT INTO `operator` (`alias`) VALUES ('BATELCO');
INSERT INTO `operator` (`alias`) VALUES ('Royal Court');
INSERT INTO `operator` (`alias`) VALUES ('Cable & Wireless (Barbados) Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('Sunbeach Communications');
INSERT INTO `operator` (`alias`) VALUES ('MDC Velcom');
INSERT INTO `operator` (`alias`) VALUES ('MTS');
INSERT INTO `operator` (`alias`) VALUES ('BelCel Joint Venture');
INSERT INTO `operator` (`alias`) VALUES ('Closed JSC Belarussian Telecommunication network');
INSERT INTO `operator` (`alias`) VALUES ('Republican Unitary Telecommunication Enterprise');
INSERT INTO `operator` (`alias`) VALUES ('YotaBel Foreign Ltd Liability Company');
INSERT INTO `operator` (`alias`) VALUES ('Proximus');
INSERT INTO `operator` (`alias`) VALUES ('Mobistar');
INSERT INTO `operator` (`alias`) VALUES ('Base');
INSERT INTO `operator` (`alias`) VALUES ('Belize Telecommunications Ltd., GSM 1900');
INSERT INTO `operator` (`alias`) VALUES ('International Telecommunications Ltd. (INTELCO)');
INSERT INTO `operator` (`alias`) VALUES ('Libercom');
INSERT INTO `operator` (`alias`) VALUES ('Telecel');
INSERT INTO `operator` (`alias`) VALUES ('Spacetel Benin');
INSERT INTO `operator` (`alias`) VALUES ('Bhutan Telecom Ltd');
INSERT INTO `operator` (`alias`) VALUES ('B-Mobile of Bhutan Telecom');
INSERT INTO `operator` (`alias`) VALUES ('Nuevatel S.A.');
INSERT INTO `operator` (`alias`) VALUES ('ENTEL S.A.');
INSERT INTO `operator` (`alias`) VALUES ('Telecel S.A.');
INSERT INTO `operator` (`alias`) VALUES ('Eronet Mobile Communications Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('MOBIS (Mobilina Srpske)');
INSERT INTO `operator` (`alias`) VALUES ('GSMBIH');
INSERT INTO `operator` (`alias`) VALUES ('Mascom Wireless (Pty) Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('Orange Botswana (Pty) Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('Botswana Telecommunications Corporation (BTC)');
INSERT INTO `operator` (`alias`) VALUES ('CRT Cellular');
INSERT INTO `operator` (`alias`) VALUES ('Global Telecom');
INSERT INTO `operator` (`alias`) VALUES ('CTMR Cel');
INSERT INTO `operator` (`alias`) VALUES ('BCP');
INSERT INTO `operator` (`alias`) VALUES ('Telesc Cel');
INSERT INTO `operator` (`alias`) VALUES ('Tess');
INSERT INTO `operator` (`alias`) VALUES ('Sercontel Cel');
INSERT INTO `operator` (`alias`) VALUES ('Maxitel MG');
INSERT INTO `operator` (`alias`) VALUES ('Telepar Cel');
INSERT INTO `operator` (`alias`) VALUES ('ATL Algar');
INSERT INTO `operator` (`alias`) VALUES ('Telems Cel');
INSERT INTO `operator` (`alias`) VALUES ('Americel');
INSERT INTO `operator` (`alias`) VALUES ('Telesp Cel');
INSERT INTO `operator` (`alias`) VALUES ('Maxitel BA');
INSERT INTO `operator` (`alias`) VALUES ('CTBC Cel');
INSERT INTO `operator` (`alias`) VALUES ('BSE');
INSERT INTO `operator` (`alias`) VALUES ('Ceterp Cel');
INSERT INTO `operator` (`alias`) VALUES ('Norte Brasil Tel');
INSERT INTO `operator` (`alias`) VALUES ('Telemig Cel');
INSERT INTO `operator` (`alias`) VALUES ('Telerj Cel');
INSERT INTO `operator` (`alias`) VALUES ('Telest Cel');
INSERT INTO `operator` (`alias`) VALUES ('Telebrasilia Cel');
INSERT INTO `operator` (`alias`) VALUES ('Telegoias Cel');
INSERT INTO `operator` (`alias`) VALUES ('Telemat Cel');
INSERT INTO `operator` (`alias`) VALUES ('Teleacre Cel');
INSERT INTO `operator` (`alias`) VALUES ('Teleron Cel');
INSERT INTO `operator` (`alias`) VALUES ('Telebahia Cel');
INSERT INTO `operator` (`alias`) VALUES ('Telergipe Cel');
INSERT INTO `operator` (`alias`) VALUES ('Telasa Cel');
INSERT INTO `operator` (`alias`) VALUES ('Telpe Cel');
INSERT INTO `operator` (`alias`) VALUES ('Telepisa Cel');
INSERT INTO `operator` (`alias`) VALUES ('Telpa Cel');
INSERT INTO `operator` (`alias`) VALUES ('Telern Cel');
INSERT INTO `operator` (`alias`) VALUES ('Teleceara Cel');
INSERT INTO `operator` (`alias`) VALUES ('Telma Cel');
INSERT INTO `operator` (`alias`) VALUES ('Telepara Cel');
INSERT INTO `operator` (`alias`) VALUES ('Teleamazon Cel');
INSERT INTO `operator` (`alias`) VALUES ('Teleamapa Cel');
INSERT INTO `operator` (`alias`) VALUES ('Telaima Cel');
INSERT INTO `operator` (`alias`) VALUES ('Cable & Wireless (BVI) Ltd');
INSERT INTO `operator` (`alias`) VALUES ('BVI Cable TV Ltd');
INSERT INTO `operator` (`alias`) VALUES ('Caribbean Cellular Telephone Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('Digicel (BVI) Ltd');
INSERT INTO `operator` (`alias`) VALUES ('DST Com');
INSERT INTO `operator` (`alias`) VALUES ('M-Tel GSM BG');
INSERT INTO `operator` (`alias`) VALUES ('Globul');
INSERT INTO `operator` (`alias`) VALUES ('Celtel');
INSERT INTO `operator` (`alias`) VALUES ('ECONET');
INSERT INTO `operator` (`alias`) VALUES ('AFRICELL');
INSERT INTO `operator` (`alias`) VALUES ('ONAMOB');
INSERT INTO `operator` (`alias`) VALUES ('LACELL');
INSERT INTO `operator` (`alias`) VALUES ('HITS TELECOM');
INSERT INTO `operator` (`alias`) VALUES ('U.COM');
INSERT INTO `operator` (`alias`) VALUES ('Mobitel (Cam GSM)');
INSERT INTO `operator` (`alias`) VALUES ('Hello');
INSERT INTO `operator` (`alias`) VALUES ('S Telecom (CDMA)');
INSERT INTO `operator` (`alias`) VALUES ('Cadcomms');
INSERT INTO `operator` (`alias`) VALUES ('Starcell');
INSERT INTO `operator` (`alias`) VALUES ('Smart');
INSERT INTO `operator` (`alias`) VALUES ('Viettel');
INSERT INTO `operator` (`alias`) VALUES ('Mfone');
INSERT INTO `operator` (`alias`) VALUES ('Orange Cameroun');
INSERT INTO `operator` (`alias`) VALUES ('Clearnet');
INSERT INTO `operator` (`alias`) VALUES ('Microcell');
INSERT INTO `operator` (`alias`) VALUES ('Ice Wireless');
INSERT INTO `operator` (`alias`) VALUES ('Aliant Mobility');
INSERT INTO `operator` (`alias`) VALUES ('Bell Mobility');
INSERT INTO `operator` (`alias`) VALUES ('Tbay Mobility');
INSERT INTO `operator` (`alias`) VALUES ('MTS Mobility');
INSERT INTO `operator` (`alias`) VALUES ('CityTel Mobility');
INSERT INTO `operator` (`alias`) VALUES ('Sask Tel Mobility');
INSERT INTO `operator` (`alias`) VALUES ('Globalstar');
INSERT INTO `operator` (`alias`) VALUES ('Rogers Wireless');
INSERT INTO `operator` (`alias`) VALUES ('Telus Mobility');
INSERT INTO `operator` (`alias`) VALUES ('Cabo Verde Telecom');
INSERT INTO `operator` (`alias`) VALUES ('T+Telecomunicações');
INSERT INTO `operator` (`alias`) VALUES ('Cable & Wireless (Cayman)');
INSERT INTO `operator` (`alias`) VALUES ('Centrafrique Telecom Plus (CTP)');
INSERT INTO `operator` (`alias`) VALUES ('Telecel Centrafrique (TC)');
INSERT INTO `operator` (`alias`) VALUES ('Celca (Socatel)');
INSERT INTO `operator` (`alias`) VALUES ('Tchad Mobile');
INSERT INTO `operator` (`alias`) VALUES ('Entel Telefónica Móvil');
INSERT INTO `operator` (`alias`) VALUES ('Telefónica Móvil');
INSERT INTO `operator` (`alias`) VALUES ('Smartcom');
INSERT INTO `operator` (`alias`) VALUES ('Centennial Cayman Corp. Chile S.A.');
INSERT INTO `operator` (`alias`) VALUES ('Multikom S.A.');
INSERT INTO `operator` (`alias`) VALUES ('Blue Two Chile SA');
INSERT INTO `operator` (`alias`) VALUES ('Telefónica Móviles Chile S.A.');
INSERT INTO `operator` (`alias`) VALUES ('VTR Móvil S.A.');
INSERT INTO `operator` (`alias`) VALUES ('Entel');
INSERT INTO `operator` (`alias`) VALUES ('Celupago S.A.');
INSERT INTO `operator` (`alias`) VALUES ('Telestar Móvil S.A.');
INSERT INTO `operator` (`alias`) VALUES ('China Unicom');
INSERT INTO `operator` (`alias`) VALUES ('China Unicom CDMA');
INSERT INTO `operator` (`alias`) VALUES ('China Satellite Global Star Network');
INSERT INTO `operator` (`alias`) VALUES ('Edatel S.A.');
INSERT INTO `operator` (`alias`) VALUES ('Emtelsa');
INSERT INTO `operator` (`alias`) VALUES ('Emcali');
INSERT INTO `operator` (`alias`) VALUES ('Comcel S.A. Occel S.A./Celcaribe');
INSERT INTO `operator` (`alias`) VALUES ('Bellsouth Colombia S.A.');
INSERT INTO `operator` (`alias`) VALUES ('Colombia Móvil S.A.');
INSERT INTO `operator` (`alias`) VALUES ('Telefónica Móviles Colombia S.A.');
INSERT INTO `operator` (`alias`) VALUES ('Avantel');
INSERT INTO `operator` (`alias`) VALUES ('HURI - SNPT');
INSERT INTO `operator` (`alias`) VALUES ('Telecom Cook');
INSERT INTO `operator` (`alias`) VALUES ('Instituto Costarricense de Electricidad - ICE');
INSERT INTO `operator` (`alias`) VALUES ('Claro CR Telecomuniocaciones S.A.');
INSERT INTO `operator` (`alias`) VALUES ('Azules y Platas S.A.');
INSERT INTO `operator` (`alias`) VALUES ('Virtualis');
INSERT INTO `operator` (`alias`) VALUES ('Atlantique Cellulaire');
INSERT INTO `operator` (`alias`) VALUES ('Orange Côte d\'Ivoire');
INSERT INTO `operator` (`alias`) VALUES ('Comium Côte d\'Ivoire');
INSERT INTO `operator` (`alias`) VALUES ('Loteny Telecom');
INSERT INTO `operator` (`alias`) VALUES ('Oricel Côte d\'Ivoire');
INSERT INTO `operator` (`alias`) VALUES ('Aircomm Côte d\'Ivoire');
INSERT INTO `operator` (`alias`) VALUES ('T-Mobile Hrvatska d.o.o./T-Mobile Croatia LLC');
INSERT INTO `operator` (`alias`) VALUES ('Tele2/Tele2 d.o.o.');
INSERT INTO `operator` (`alias`) VALUES ('ETECSA');
INSERT INTO `operator` (`alias`) VALUES ('TELCELL GSM');
INSERT INTO `operator` (`alias`) VALUES ('CT GSM');
INSERT INTO `operator` (`alias`) VALUES ('CYTA');
INSERT INTO `operator` (`alias`) VALUES ('Scancom (Cyprus) Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('Primetel PLC');
INSERT INTO `operator` (`alias`) VALUES ('T-Mobile Czech Republic a.s.');
INSERT INTO `operator` (`alias`) VALUES ('Telefónica O2 Czech Republic a.s.');
INSERT INTO `operator` (`alias`) VALUES ('Vodafone Czech Republic a.s.');
INSERT INTO `operator` (`alias`) VALUES ('Mobilkom a.s.');
INSERT INTO `operator` (`alias`) VALUES ('Travel Telekommunikation, sro');
INSERT INTO `operator` (`alias`) VALUES ('Sprava Zeleznicni Dopravni Cesty');
INSERT INTO `operator` (`alias`) VALUES ('Vodafone Czech Republic a.s. R&D Centre');
INSERT INTO `operator` (`alias`) VALUES ('Vodacom Congo RDC sprl');
INSERT INTO `operator` (`alias`) VALUES ('Airtel sprl');
INSERT INTO `operator` (`alias`) VALUES ('Supercell Sprl');
INSERT INTO `operator` (`alias`) VALUES ('Congo-Chine Telecom s.a.r.l.');
INSERT INTO `operator` (`alias`) VALUES ('Yozma Timerus sprl');
INSERT INTO `operator` (`alias`) VALUES ('Oasis sprl');
INSERT INTO `operator` (`alias`) VALUES ('TDC Mobil');
INSERT INTO `operator` (`alias`) VALUES ('Sonofon');
INSERT INTO `operator` (`alias`) VALUES ('MIGway A/S');
INSERT INTO `operator` (`alias`) VALUES ('Hi3G');
INSERT INTO `operator` (`alias`) VALUES ('Barablu Mobile Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('Lycamobile Denmark');
INSERT INTO `operator` (`alias`) VALUES ('Telia');
INSERT INTO `operator` (`alias`) VALUES ('Telia Mobile');
INSERT INTO `operator` (`alias`) VALUES ('Tele2');
INSERT INTO `operator` (`alias`) VALUES ('Evatis');
INSERT INTO `operator` (`alias`) VALUES ('Orange Dominicana, S.A.');
INSERT INTO `operator` (`alias`) VALUES ('Verizon Dominicana S.A.');
INSERT INTO `operator` (`alias`) VALUES ('Tricom S.A.');
INSERT INTO `operator` (`alias`) VALUES ('CentennialDominicana');
INSERT INTO `operator` (`alias`) VALUES ('Porta GSM');
INSERT INTO `operator` (`alias`) VALUES ('Telecsa S.A.');
INSERT INTO `operator` (`alias`) VALUES ('Mobinil');
INSERT INTO `operator` (`alias`) VALUES ('Vodafone');
INSERT INTO `operator` (`alias`) VALUES ('Etisalat');
INSERT INTO `operator` (`alias`) VALUES ('CTE Telecom Personal, S.A. de C.V.');
INSERT INTO `operator` (`alias`) VALUES ('Digicel, S.A. de C.V.');
INSERT INTO `operator` (`alias`) VALUES ('Telemóvil El Salvador, S.A.');
INSERT INTO `operator` (`alias`) VALUES ('Guinea Ecuatorial de Telecomunicaciones Sociedad Annima');
INSERT INTO `operator` (`alias`) VALUES ('EMT GSM');
INSERT INTO `operator` (`alias`) VALUES ('RLE');
INSERT INTO `operator` (`alias`) VALUES ('AS Bravocom Mobiil');
INSERT INTO `operator` (`alias`) VALUES ('ProGroup Holding OY');
INSERT INTO `operator` (`alias`) VALUES ('Televargu AS');
INSERT INTO `operator` (`alias`) VALUES ('Siseministeerium (Ministry of Interior)');
INSERT INTO `operator` (`alias`) VALUES ('ETH MTN');
INSERT INTO `operator` (`alias`) VALUES ('Touch');
INSERT INTO `operator` (`alias`) VALUES ('Faroese Telecom - GSM');
INSERT INTO `operator` (`alias`) VALUES ('Kall GSM');
INSERT INTO `operator` (`alias`) VALUES ('Edge Mobile Sp/F');
INSERT INTO `operator` (`alias`) VALUES ('Vodafone (Fiji) Ltd');
INSERT INTO `operator` (`alias`) VALUES ('Digicel (Fiji) Ltd');
INSERT INTO `operator` (`alias`) VALUES ('Telecom Fiji Ltd (CDMA)');
INSERT INTO `operator` (`alias`) VALUES ('DNA Oy');
INSERT INTO `operator` (`alias`) VALUES ('Elisa Oy');
INSERT INTO `operator` (`alias`) VALUES ('Nokia Siemens Networks Oy');
INSERT INTO `operator` (`alias`) VALUES ('TDC Oy Finland');
INSERT INTO `operator` (`alias`) VALUES ('Alands Mobiltelefon AB');
INSERT INTO `operator` (`alias`) VALUES ('Saunalahti Group Oyj');
INSERT INTO `operator` (`alias`) VALUES ('SCNL Truphone');
INSERT INTO `operator` (`alias`) VALUES ('TeliaSonera Finland Oyj');
INSERT INTO `operator` (`alias`) VALUES ('Globalstar Europe');
INSERT INTO `operator` (`alias`) VALUES ('S.F.R.');
INSERT INTO `operator` (`alias`) VALUES ('S.F.R. (UMTS)');
INSERT INTO `operator` (`alias`) VALUES ('SFR (Zones Blanches)');
INSERT INTO `operator` (`alias`) VALUES ('Bouygues Telecom');
INSERT INTO `operator` (`alias`) VALUES ('Transatel');
INSERT INTO `operator` (`alias`) VALUES ('Bouygues Telecom (Zones Blanches)');
INSERT INTO `operator` (`alias`) VALUES ('Outremer Telecom');
INSERT INTO `operator` (`alias`) VALUES ('Société Réunionnaise du Radiotéléphone');
INSERT INTO `operator` (`alias`) VALUES ('Guyane Téléphone Mobile');
INSERT INTO `operator` (`alias`) VALUES ('Digicel Tahiti');
INSERT INTO `operator` (`alias`) VALUES ('Mara Telecom');
INSERT INTO `operator` (`alias`) VALUES ('Tikiphone');
INSERT INTO `operator` (`alias`) VALUES ('Libertis S.A.');
INSERT INTO `operator` (`alias`) VALUES ('Celtel Gabon S.A.');
INSERT INTO `operator` (`alias`) VALUES ('USAN Gabon');
INSERT INTO `operator` (`alias`) VALUES ('Gamcel');
INSERT INTO `operator` (`alias`) VALUES ('Magti GSM Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('Iberiatel Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('Mobitel Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('Silknet JSC');
INSERT INTO `operator` (`alias`) VALUES ('T-Mobile Deutschland GmbH');
INSERT INTO `operator` (`alias`) VALUES ('E-Plus Mobilfunk GmbH & Co. KG');
INSERT INTO `operator` (`alias`) VALUES ('Dolphin Telecom (Deutschland) GmbH');
INSERT INTO `operator` (`alias`) VALUES ('Mobilcom Multimedia GmbH');
INSERT INTO `operator` (`alias`) VALUES ('Group 3G UMTS GmbH (Quam)');
INSERT INTO `operator` (`alias`) VALUES ('Airdata AG');
INSERT INTO `operator` (`alias`) VALUES ('Spacefon');
INSERT INTO `operator` (`alias`) VALUES ('Ghana Telecom Mobile');
INSERT INTO `operator` (`alias`) VALUES ('Mobitel');
INSERT INTO `operator` (`alias`) VALUES ('Kasapa Telecom Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('Netafriques Dot Com Ltd');
INSERT INTO `operator` (`alias`) VALUES ('Gibtelecom GSM');
INSERT INTO `operator` (`alias`) VALUES ('CTS');
INSERT INTO `operator` (`alias`) VALUES ('Eazi Telecom Ltd');
INSERT INTO `operator` (`alias`) VALUES ('Cosmote');
INSERT INTO `operator` (`alias`) VALUES ('OTE');
INSERT INTO `operator` (`alias`) VALUES ('EDISY');
INSERT INTO `operator` (`alias`) VALUES ('Vodafone - Panafon');
INSERT INTO `operator` (`alias`) VALUES ('COSMOLINE');
INSERT INTO `operator` (`alias`) VALUES ('WIND');
INSERT INTO `operator` (`alias`) VALUES ('Tele Greenland');
INSERT INTO `operator` (`alias`) VALUES ('Orange Carabe Mobiles');
INSERT INTO `operator` (`alias`) VALUES ('Saint Martin et Saint Barthelemy Telcell Sarl');
INSERT INTO `operator` (`alias`) VALUES ('Dauphin Telecom');
INSERT INTO `operator` (`alias`) VALUES ('Guadeloupe Téléphone Mobile');
INSERT INTO `operator` (`alias`) VALUES ('Bouygues Telecom Caraïbe');
INSERT INTO `operator` (`alias`) VALUES ('Servicios de Comunicaciones Personales Inalmbricas, S.A.');
INSERT INTO `operator` (`alias`) VALUES ('Comunicaciones Celulares S.A.');
INSERT INTO `operator` (`alias`) VALUES ('Cellcom Guinée SA');
INSERT INTO `operator` (`alias`) VALUES ('Cel*Star (Guyana) Inc.');
INSERT INTO `operator` (`alias`) VALUES ('Digicel');
INSERT INTO `operator` (`alias`) VALUES ('Rectel');
INSERT INTO `operator` (`alias`) VALUES ('Megatel');
INSERT INTO `operator` (`alias`) VALUES ('Digicel Honduras');
INSERT INTO `operator` (`alias`) VALUES ('MVNO/CITIC');
INSERT INTO `operator` (`alias`) VALUES ('3G Radio System/Hutchison 3G');
INSERT INTO `operator` (`alias`) VALUES ('GSM900/GSM1800/Hutchison');
INSERT INTO `operator` (`alias`) VALUES ('CDMA/Hutchison');
INSERT INTO `operator` (`alias`) VALUES ('GSM900/SmarTone');
INSERT INTO `operator` (`alias`) VALUES ('MVNO/China Unicom International Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('MVNO/Trident');
INSERT INTO `operator` (`alias`) VALUES ('MVNO/China Motion Telecom (HK) Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('GSM1800New World PCS Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('MVNO/CHKTL');
INSERT INTO `operator` (`alias`) VALUES ('3G Radio System/SMT3G');
INSERT INTO `operator` (`alias`) VALUES ('GSM1800/Mandarin Communications Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('GSM7800/Hong Kong CSL Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('3G Radio System/Sunday3G');
INSERT INTO `operator` (`alias`) VALUES ('Public Mobile Networks/Reserved');
INSERT INTO `operator` (`alias`) VALUES ('Pannon GSM');
INSERT INTO `operator` (`alias`) VALUES ('Iceland Telecom Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('Og fjarskipti hf (Vodafone Iceland)');
INSERT INTO `operator` (`alias`) VALUES ('IceCell ehf');
INSERT INTO `operator` (`alias`) VALUES ('Aircell Digilink India Ltd., Haryana');
INSERT INTO `operator` (`alias`) VALUES ('Bharti Airtel Ltd., Punjab');
INSERT INTO `operator` (`alias`) VALUES ('Bharti Airtel Ltd., H.P.');
INSERT INTO `operator` (`alias`) VALUES ('Idea Cellular Ltd., Delhi');
INSERT INTO `operator` (`alias`) VALUES ('Fascel Ltd., Gujarat');
INSERT INTO `operator` (`alias`) VALUES ('Bharti Airtel Ltd., Karnataka');
INSERT INTO `operator` (`alias`) VALUES ('Idea Cellular Ltd., Andhra Pradesh');
INSERT INTO `operator` (`alias`) VALUES ('Reliance Telecom Ltd., Assam');
INSERT INTO `operator` (`alias`) VALUES ('Bharti Airtel Ltd., Delhi');
INSERT INTO `operator` (`alias`) VALUES ('Hutchison Essar Mobile Services Ltd, Delhi');
INSERT INTO `operator` (`alias`) VALUES ('Idea Mobile Communications Ltd., Haryana');
INSERT INTO `operator` (`alias`) VALUES ('Hutchinson Essar South Ltd., Andhra Pradesh');
INSERT INTO `operator` (`alias`) VALUES ('Spice Communications PVT Ltd., Punjab');
INSERT INTO `operator` (`alias`) VALUES ('Aircell Digilink India Ltd., UP (East)');
INSERT INTO `operator` (`alias`) VALUES ('Bharti Airtel Ltd, North East');
INSERT INTO `operator` (`alias`) VALUES ('Dishnet Wireless Ltd, West Bengal');
INSERT INTO `operator` (`alias`) VALUES ('Idea Mobile Communications Ltd., Kerala');
INSERT INTO `operator` (`alias`) VALUES ('Hutchinson Essar Ltd, Mumbai');
INSERT INTO `operator` (`alias`) VALUES ('BPL Mobile Communications Ltd., Mumbai');
INSERT INTO `operator` (`alias`) VALUES ('Idea Cellular Ltd., Maharashtra');
INSERT INTO `operator` (`alias`) VALUES ('Idea Cellular Ltd, Maharashtra');
INSERT INTO `operator` (`alias`) VALUES ('Idea Cellular Ltd., Gujarat');
INSERT INTO `operator` (`alias`) VALUES ('Dishnet Wireless Ltd, Bihar');
INSERT INTO `operator` (`alias`) VALUES ('Hutchison Essar Cellular Ltd., Maharashtra');
INSERT INTO `operator` (`alias`) VALUES ('Dishnet Wireless Ltd, Assam');
INSERT INTO `operator` (`alias`) VALUES ('Hutchison Telecom East Ltd, Kolkata');
INSERT INTO `operator` (`alias`) VALUES ('Bharti Airtel Ltd., Kolkata');
INSERT INTO `operator` (`alias`) VALUES ('Dishnet Wireless Ltd, North East');
INSERT INTO `operator` (`alias`) VALUES ('BSNL, Haryana');
INSERT INTO `operator` (`alias`) VALUES ('Dishnet Wireless Ltd, Himachal Pradesh');
INSERT INTO `operator` (`alias`) VALUES ('Reliance Telecom Ltd., Bihar');
INSERT INTO `operator` (`alias`) VALUES ('Dishnet Wireless Ltd, J&K');
INSERT INTO `operator` (`alias`) VALUES ('BSNL, Assam');
INSERT INTO `operator` (`alias`) VALUES ('Bharti Airtel Ltd., Chennai');
INSERT INTO `operator` (`alias`) VALUES ('Aircel Ltd., Tamil Nadu');
INSERT INTO `operator` (`alias`) VALUES ('Hutchison Essar Cellular Ltd., Tamil Nadu');
INSERT INTO `operator` (`alias`) VALUES ('Hutchison Essar Cellular Ltd., Kerala');
INSERT INTO `operator` (`alias`) VALUES ('Dishnet Wireless Ltd, UP (West)');
INSERT INTO `operator` (`alias`) VALUES ('Reliance Telecom Ltd., North East');
INSERT INTO `operator` (`alias`) VALUES ('BSNL, H.P.');
INSERT INTO `operator` (`alias`) VALUES ('Reliance TelecomLtd., Orissa');
INSERT INTO `operator` (`alias`) VALUES ('BSNL, Punjab');
INSERT INTO `operator` (`alias`) VALUES ('BSNL, UP (West)');
INSERT INTO `operator` (`alias`) VALUES ('BSNL, UP (East)');
INSERT INTO `operator` (`alias`) VALUES ('Idea Mobile Communications Ltd., UP (West)');
INSERT INTO `operator` (`alias`) VALUES ('BSNL, Gujarat');
INSERT INTO `operator` (`alias`) VALUES ('BSNL, Madhya Pradesh');
INSERT INTO `operator` (`alias`) VALUES ('BSNL, Rajasthan');
INSERT INTO `operator` (`alias`) VALUES ('Aircell Digilink India Ltd., Rajasthan');
INSERT INTO `operator` (`alias`) VALUES ('Dishnet Wireless Ltd, Punjab');
INSERT INTO `operator` (`alias`) VALUES ('BSNL, J&K');
INSERT INTO `operator` (`alias`) VALUES ('Dishnet Wireless Ltd, Haryana');
INSERT INTO `operator` (`alias`) VALUES ('BSNL, Chennai');
INSERT INTO `operator` (`alias`) VALUES ('Dishnet Wireless Ltd, UP (East)');
INSERT INTO `operator` (`alias`) VALUES ('BSNL, Maharashtra');
INSERT INTO `operator` (`alias`) VALUES ('Reliance Telecom Ltd., Madhya Pradesh');
INSERT INTO `operator` (`alias`) VALUES ('MTNL, Delhi');
INSERT INTO `operator` (`alias`) VALUES ('MTNL, Mumbai');
INSERT INTO `operator` (`alias`) VALUES ('Bharti Hexacom Ltd, Rajasthan');
INSERT INTO `operator` (`alias`) VALUES ('BSNL, Karnataka');
INSERT INTO `operator` (`alias`) VALUES ('BSNL, Kerala');
INSERT INTO `operator` (`alias`) VALUES ('BSNL, Andhra Pradesh');
INSERT INTO `operator` (`alias`) VALUES ('BSNL, West Bengal');
INSERT INTO `operator` (`alias`) VALUES ('BSNL, Bihar');
INSERT INTO `operator` (`alias`) VALUES ('BSNL, Orissa');
INSERT INTO `operator` (`alias`) VALUES ('BSNL, North East');
INSERT INTO `operator` (`alias`) VALUES ('BTA Cellcom Ltd., Madhya Pradesh');
INSERT INTO `operator` (`alias`) VALUES ('BSNL, Andaman & Nicobar');
INSERT INTO `operator` (`alias`) VALUES ('BSNL, Tamil Nadu');
INSERT INTO `operator` (`alias`) VALUES ('BSNL, Kolkata');
INSERT INTO `operator` (`alias`) VALUES ('Idea Telecommunications Ltd, H.P.');
INSERT INTO `operator` (`alias`) VALUES ('Reliable Internet Services Ltd., Kolkata');
INSERT INTO `operator` (`alias`) VALUES ('Hutchinson Essar South Ltd., Chennai');
INSERT INTO `operator` (`alias`) VALUES ('Reliance Telecom Ltd., W.B. & A.N.');
INSERT INTO `operator` (`alias`) VALUES ('Hutchinson Essar South Ltd., Karnataka');
INSERT INTO `operator` (`alias`) VALUES ('Idea Telecommunications Ltd, Rajasthan');
INSERT INTO `operator` (`alias`) VALUES ('Hutchison Essar South Ltd, Punjab');
INSERT INTO `operator` (`alias`) VALUES ('Idea Telecommunications Ltd, UP (East)');
INSERT INTO `operator` (`alias`) VALUES ('Bharti Airtel Ltd., Maharashtra');
INSERT INTO `operator` (`alias`) VALUES ('Dishnet Wireless Ltd, Kolkata');
INSERT INTO `operator` (`alias`) VALUES ('Bharti Airtel Ltd., Mumbai');
INSERT INTO `operator` (`alias`) VALUES ('Bharti Airtel Ltd., Madhya Pradesh');
INSERT INTO `operator` (`alias`) VALUES ('Bharti Airtel Ltd., Tamil Nadu');
INSERT INTO `operator` (`alias`) VALUES ('Bharti Airtel Ltd., Kerala');
INSERT INTO `operator` (`alias`) VALUES ('Bharti Airtel Ltd., Haryana');
INSERT INTO `operator` (`alias`) VALUES ('Bharti Airtel Ltd., UP (West)');
INSERT INTO `operator` (`alias`) VALUES ('Bharti Airtel Ltd., Gujarat');
INSERT INTO `operator` (`alias`) VALUES ('Dishnet Wireless Ltd, Kerala');
INSERT INTO `operator` (`alias`) VALUES ('Reliance Infocomm Ltd, Andhra Pradesh');
INSERT INTO `operator` (`alias`) VALUES ('Reliance Infocomm Ltd, Bihar');
INSERT INTO `operator` (`alias`) VALUES ('Reliance Infocomm Ltd, Chennai');
INSERT INTO `operator` (`alias`) VALUES ('Reliance Infocomm Ltd, Delhi');
INSERT INTO `operator` (`alias`) VALUES ('Reliance Infocomm Ltd, Gujarat');
INSERT INTO `operator` (`alias`) VALUES ('Reliance Infocomm Ltd, Haryana');
INSERT INTO `operator` (`alias`) VALUES ('Reliance Infocomm Ltd, Himachal Pradesh');
INSERT INTO `operator` (`alias`) VALUES ('Reliance Infocomm Ltd, J&K');
INSERT INTO `operator` (`alias`) VALUES ('Reliance Infocomm Ltd, Karnataka');
INSERT INTO `operator` (`alias`) VALUES ('Reliance Infocomm Ltd, Kerala');
INSERT INTO `operator` (`alias`) VALUES ('Reliance Infocomm Ltd, Kolkata');
INSERT INTO `operator` (`alias`) VALUES ('Reliance Infocomm Ltd, Maharashtra');
INSERT INTO `operator` (`alias`) VALUES ('Reliance Infocomm Ltd, Madhya Pradesh');
INSERT INTO `operator` (`alias`) VALUES ('Reliance Infocomm Ltd, Mumbai');
INSERT INTO `operator` (`alias`) VALUES ('Reliance Infocomm Ltd, Orissa');
INSERT INTO `operator` (`alias`) VALUES ('Reliance Infocomm Ltd, Punjab');
INSERT INTO `operator` (`alias`) VALUES ('Reliance Infocomm Ltd, Tamilnadu');
INSERT INTO `operator` (`alias`) VALUES ('Reliance Infocomm Ltd, UP (East)');
INSERT INTO `operator` (`alias`) VALUES ('Reliance Infocomm Ltd, UP (West)');
INSERT INTO `operator` (`alias`) VALUES ('Reliance Infocomm Ltd, West bengal');
INSERT INTO `operator` (`alias`) VALUES ('Tata Teleservices Ltd, Andhra Pradesh');
INSERT INTO `operator` (`alias`) VALUES ('Tata Teleservices Ltd, Bihar');
INSERT INTO `operator` (`alias`) VALUES ('Tata Teleservices Ltd, Chennai');
INSERT INTO `operator` (`alias`) VALUES ('Tata Teleservices Ltd, Delhi');
INSERT INTO `operator` (`alias`) VALUES ('Tata Teleservices Ltd, Gujarat');
INSERT INTO `operator` (`alias`) VALUES ('Tata Teleservices Ltd, Haryana');
INSERT INTO `operator` (`alias`) VALUES ('Tata Teleservices Ltd, Himachal Pradesh');
INSERT INTO `operator` (`alias`) VALUES ('Tata Teleservices Ltd, Karnataka');
INSERT INTO `operator` (`alias`) VALUES ('Tata Teleservices Ltd, Kerala');
INSERT INTO `operator` (`alias`) VALUES ('Tata Teleservices Ltd, Kolkata');
INSERT INTO `operator` (`alias`) VALUES ('Tata Teleservices Ltd, Maharashtra');
INSERT INTO `operator` (`alias`) VALUES ('Tata Teleservices Ltd, Madhya Pradesh');
INSERT INTO `operator` (`alias`) VALUES ('Tata Teleservices Ltd, Mumbai');
INSERT INTO `operator` (`alias`) VALUES ('Tata Teleservices Ltd, Orissa');
INSERT INTO `operator` (`alias`) VALUES ('Tata Teleservices Ltd, Punjab');
INSERT INTO `operator` (`alias`) VALUES ('Tata Teleservices Ltd, Rajasthan');
INSERT INTO `operator` (`alias`) VALUES ('Tata Teleservices Ltd, Tamilnadu');
INSERT INTO `operator` (`alias`) VALUES ('Tata Teleservices Ltd, UP (East)');
INSERT INTO `operator` (`alias`) VALUES ('Tata Teleservices Ltd, UP (West)');
INSERT INTO `operator` (`alias`) VALUES ('Tata Teleservices Ltd, West Bengal');
INSERT INTO `operator` (`alias`) VALUES ('Bharti Airtel Ltd, Bihar');
INSERT INTO `operator` (`alias`) VALUES ('Bharti Airtel Ltd, Orissa');
INSERT INTO `operator` (`alias`) VALUES ('Bharti Airtel Ltd, UP (East)');
INSERT INTO `operator` (`alias`) VALUES ('Bharti Airtel Ltd, J&K');
INSERT INTO `operator` (`alias`) VALUES ('Bharti Airtel Ltd, Assam');
INSERT INTO `operator` (`alias`) VALUES ('Hutchison Essar South Ltd, UP (West)');
INSERT INTO `operator` (`alias`) VALUES ('Hutchison Essar South Ltd, Orissa');
INSERT INTO `operator` (`alias`) VALUES ('Vodaphone/Hutchison, Madhya Pradesh');
INSERT INTO `operator` (`alias`) VALUES ('Aditya Birla Telecom Ltd, Bihar');
INSERT INTO `operator` (`alias`) VALUES ('Essar Spacetel Ltd, Himachal Pradesh');
INSERT INTO `operator` (`alias`) VALUES ('Essar Spacetel Ltd, North East');
INSERT INTO `operator` (`alias`) VALUES ('Essar Spacetel Ltd, Assam');
INSERT INTO `operator` (`alias`) VALUES ('Essar Spacetel Ltd, J&K');
INSERT INTO `operator` (`alias`) VALUES ('Essar Spacetel Ltd, Bihar');
INSERT INTO `operator` (`alias`) VALUES ('Essar Spacetel Ltd, Orissa');
INSERT INTO `operator` (`alias`) VALUES ('Essar Spacetel Ltd, Maharashtra');
INSERT INTO `operator` (`alias`) VALUES ('Aircell Ltd, Karnataka');
INSERT INTO `operator` (`alias`) VALUES ('Aircell Ltd, Delhi');
INSERT INTO `operator` (`alias`) VALUES ('Aircell Ltd, Andhra Pradesh');
INSERT INTO `operator` (`alias`) VALUES ('Aircell Ltd, Gujarat');
INSERT INTO `operator` (`alias`) VALUES ('Aircell Ltd, Maharashtra');
INSERT INTO `operator` (`alias`) VALUES ('Aircell Ltd, Mumbai');
INSERT INTO `operator` (`alias`) VALUES ('Aircell Ltd, Rajasthan');
INSERT INTO `operator` (`alias`) VALUES ('Satelindo');
INSERT INTO `operator` (`alias`) VALUES ('Natrindo (Lippo Telecom)');
INSERT INTO `operator` (`alias`) VALUES ('Telkomsel');
INSERT INTO `operator` (`alias`) VALUES ('Excelcomindo');
INSERT INTO `operator` (`alias`) VALUES ('Indosat - M3');
INSERT INTO `operator` (`alias`) VALUES ('Komselindo');
INSERT INTO `operator` (`alias`) VALUES ('ICO Global Communications');
INSERT INTO `operator` (`alias`) VALUES ('Iridium Communications Inc');
INSERT INTO `operator` (`alias`) VALUES ('Thuraya RMSS Network');
INSERT INTO `operator` (`alias`) VALUES ('Thuraya Satellite Telecommunications Company');
INSERT INTO `operator` (`alias`) VALUES ('Asia Cellular Satellite (AceS)');
INSERT INTO `operator` (`alias`) VALUES ('Inmarsat Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('Maritime Communications Partner AS (MCP network)');
INSERT INTO `operator` (`alias`) VALUES ('BebbiCell AG');
INSERT INTO `operator` (`alias`) VALUES ('Telenor');
INSERT INTO `operator` (`alias`) VALUES ('OnAir');
INSERT INTO `operator` (`alias`) VALUES ('Jasper Wireless, Inc');
INSERT INTO `operator` (`alias`) VALUES ('Jersey Telecom');
INSERT INTO `operator` (`alias`) VALUES ('Cingular Wireless');
INSERT INTO `operator` (`alias`) VALUES ('Vodafone Malta (Vodafone Group)');
INSERT INTO `operator` (`alias`) VALUES ('Intermatica');
INSERT INTO `operator` (`alias`) VALUES ('Seanet Maritime Communications AB');
INSERT INTO `operator` (`alias`) VALUES ('MediaLincc Ltd');
INSERT INTO `operator` (`alias`) VALUES ('Beeline');
INSERT INTO `operator` (`alias`) VALUES ('Voxbone SA');
INSERT INTO `operator` (`alias`) VALUES ('Telecom Italia');
INSERT INTO `operator` (`alias`) VALUES ('Vodafone Group');
INSERT INTO `operator` (`alias`) VALUES ('Telenor Connexion AB');
INSERT INTO `operator` (`alias`) VALUES ('France Telecom Orange');
INSERT INTO `operator` (`alias`) VALUES ('Megafon');
INSERT INTO `operator` (`alias`) VALUES ('Smart Communications, Inc');
INSERT INTO `operator` (`alias`) VALUES ('UN Office for the Coordination of Humanitarian Affairs (OCHA)');
INSERT INTO `operator` (`alias`) VALUES ('Telecommunication Company of Iran (TCI)');
INSERT INTO `operator` (`alias`) VALUES ('Telecommunication Kish Co. (KIFZO)');
INSERT INTO `operator` (`alias`) VALUES ('Telecommunication Company of Iran (TCI) - Isfahan Celcom');
INSERT INTO `operator` (`alias`) VALUES ('Asia Cell');
INSERT INTO `operator` (`alias`) VALUES ('Zain Iraq (previously Atheer)');
INSERT INTO `operator` (`alias`) VALUES ('Zain Iraq (previously Iraqna)');
INSERT INTO `operator` (`alias`) VALUES ('Korek Telecom');
INSERT INTO `operator` (`alias`) VALUES ('Iraq Central Cooperative Association for Communication and Transportation');
INSERT INTO `operator` (`alias`) VALUES ('ITC Fanoos');
INSERT INTO `operator` (`alias`) VALUES ('Iraqtel');
INSERT INTO `operator` (`alias`) VALUES ('Itisaluna');
INSERT INTO `operator` (`alias`) VALUES ('Kalimat');
INSERT INTO `operator` (`alias`) VALUES ('Iraqi Telecommunications & Post Company (ITPC)');
INSERT INTO `operator` (`alias`) VALUES ('ITPC (Al-Mazaya)');
INSERT INTO `operator` (`alias`) VALUES ('ITPC (Sader Al-Iraq)');
INSERT INTO `operator` (`alias`) VALUES ('ITPC (Eaamar Albasrah)');
INSERT INTO `operator` (`alias`) VALUES ('ITPC (Anwar Yagotat Alkhalee)');
INSERT INTO `operator` (`alias`) VALUES ('ITPC (Furatfone)');
INSERT INTO `operator` (`alias`) VALUES ('ITPC (Al-Seraj)');
INSERT INTO `operator` (`alias`) VALUES ('ITPC (High Link)');
INSERT INTO `operator` (`alias`) VALUES ('ITPC (Al-Shams)');
INSERT INTO `operator` (`alias`) VALUES ('ITPC (Belad Babel)');
INSERT INTO `operator` (`alias`) VALUES ('ITPC (Al Nakheel)');
INSERT INTO `operator` (`alias`) VALUES ('ITPC (Iraqcell)');
INSERT INTO `operator` (`alias`) VALUES ('ITPC (Shaly)');
INSERT INTO `operator` (`alias`) VALUES ('Vodafone Ireland Plc');
INSERT INTO `operator` (`alias`) VALUES ('Digifone mm02 Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('Meteor Mobile Communications Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('Eircom');
INSERT INTO `operator` (`alias`) VALUES ('Clever Communications Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('Partner Communications Co. Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('Cellcom Israel Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('Pelephone Communications Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('Globalsim Ltd');
INSERT INTO `operator` (`alias`) VALUES ('Wataniya');
INSERT INTO `operator` (`alias`) VALUES ('Mirs Ltd');
INSERT INTO `operator` (`alias`) VALUES ('Golan Telecom Ltd');
INSERT INTO `operator` (`alias`) VALUES ('365 Telecom (MVNO)');
INSERT INTO `operator` (`alias`) VALUES ('Ituran Cellular Communications');
INSERT INTO `operator` (`alias`) VALUES ('Alon Cellular Ltd');
INSERT INTO `operator` (`alias`) VALUES ('Home Cellular (MVNO)');
INSERT INTO `operator` (`alias`) VALUES ('Rami Levi (MVNO)');
INSERT INTO `operator` (`alias`) VALUES ('Gale Phone (MVNO)');
INSERT INTO `operator` (`alias`) VALUES ('Telecom Italia Mobile (TIM)');
INSERT INTO `operator` (`alias`) VALUES ('Elsacom');
INSERT INTO `operator` (`alias`) VALUES ('Omnitel Pronto Italia (OPI)');
INSERT INTO `operator` (`alias`) VALUES ('IPSE 2000');
INSERT INTO `operator` (`alias`) VALUES ('Blu');
INSERT INTO `operator` (`alias`) VALUES ('H3G');
INSERT INTO `operator` (`alias`) VALUES ('Cable & Wireless Jamaica Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('Mossel (Jamaica) Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('NTT DoCoMo, Inc.');
INSERT INTO `operator` (`alias`) VALUES ('NTT DoCoMo Kansai, Inc.');
INSERT INTO `operator` (`alias`) VALUES ('NTT DoCoMo Hokuriku, Inc.');
INSERT INTO `operator` (`alias`) VALUES ('KDDI Corporation');
INSERT INTO `operator` (`alias`) VALUES ('NTT DoCoMo Kansai Inc.');
INSERT INTO `operator` (`alias`) VALUES ('NTT DoCoMo Tokai Inc.');
INSERT INTO `operator` (`alias`) VALUES ('NTT DoCoMo Inc.');
INSERT INTO `operator` (`alias`) VALUES ('NTT DoCoMo Tohoku Inc.');
INSERT INTO `operator` (`alias`) VALUES ('NTT DoCoMo Hokkaido');
INSERT INTO `operator` (`alias`) VALUES ('NTT DoCoMo Hokuriku Inc.');
INSERT INTO `operator` (`alias`) VALUES ('NTT DoCoMo Chugoku Inc.');
INSERT INTO `operator` (`alias`) VALUES ('NTT DoCoMo Hokkaido Inc.');
INSERT INTO `operator` (`alias`) VALUES ('NTT DoCoMo Kyushu Inc.');
INSERT INTO `operator` (`alias`) VALUES ('NTT DoCoMoTohoku Inc.');
INSERT INTO `operator` (`alias`) VALUES ('NTT DoCoMo Shikoku Inc.');
INSERT INTO `operator` (`alias`) VALUES ('Okinawa Cellular Telephone');
INSERT INTO `operator` (`alias`) VALUES ('TU-KA Cellular Tokyo Inc.');
INSERT INTO `operator` (`alias`) VALUES ('TU-KA Phone Kansai Inc.');
INSERT INTO `operator` (`alias`) VALUES ('TU-KA Cellular Tokai Inc.');
INSERT INTO `operator` (`alias`) VALUES ('Fastlink');
INSERT INTO `operator` (`alias`) VALUES ('Xpress');
INSERT INTO `operator` (`alias`) VALUES ('Umniah');
INSERT INTO `operator` (`alias`) VALUES ('Mobilecom');
INSERT INTO `operator` (`alias`) VALUES ('Kar-Tel llc');
INSERT INTO `operator` (`alias`) VALUES ('TSC Kazak Telecom');
INSERT INTO `operator` (`alias`) VALUES ('Safaricom Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('Kencell Communications Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('KT Freetel');
INSERT INTO `operator` (`alias`) VALUES ('SK Telecom');
INSERT INTO `operator` (`alias`) VALUES ('Mobile Telecommunications Company');
INSERT INTO `operator` (`alias`) VALUES ('Wataniya Telecom');
INSERT INTO `operator` (`alias`) VALUES ('Viva');
INSERT INTO `operator` (`alias`) VALUES ('Bitel GSM');
INSERT INTO `operator` (`alias`) VALUES ('Lao Telecommunications');
INSERT INTO `operator` (`alias`) VALUES ('ETL Mobile');
INSERT INTO `operator` (`alias`) VALUES ('Millicom');
INSERT INTO `operator` (`alias`) VALUES ('Latvijas Mobilais Telefons SIA');
INSERT INTO `operator` (`alias`) VALUES ('Telekom Baltija');
INSERT INTO `operator` (`alias`) VALUES ('Beta Telecom');
INSERT INTO `operator` (`alias`) VALUES ('Bite Mobile');
INSERT INTO `operator` (`alias`) VALUES ('Rigatta');
INSERT INTO `operator` (`alias`) VALUES ('IZZI');
INSERT INTO `operator` (`alias`) VALUES ('Ogero Telecom');
INSERT INTO `operator` (`alias`) VALUES ('Cellis');
INSERT INTO `operator` (`alias`) VALUES ('Libancell');
INSERT INTO `operator` (`alias`) VALUES ('Vodacom Lesotho (pty) Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('Econet Ezin-cel');
INSERT INTO `operator` (`alias`) VALUES ('Comium Liberia');
INSERT INTO `operator` (`alias`) VALUES ('Mobilkom (Liechstein) AG');
INSERT INTO `operator` (`alias`) VALUES ('Omnitel');
INSERT INTO `operator` (`alias`) VALUES ('P&T Luxembourg');
INSERT INTO `operator` (`alias`) VALUES ('Tango');
INSERT INTO `operator` (`alias`) VALUES ('CTM GSM');
INSERT INTO `operator` (`alias`) VALUES ('Telecom Malagasy Mobile, GSM');
INSERT INTO `operator` (`alias`) VALUES ('Telekom Network Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('Celcom (Malaysia) Berhad');
INSERT INTO `operator` (`alias`) VALUES ('Telekom Malaysia Berhad');
INSERT INTO `operator` (`alias`) VALUES ('U Mobile Sdn. Bhd.');
INSERT INTO `operator` (`alias`) VALUES ('Electcoms Wireless Sdn Bhd');
INSERT INTO `operator` (`alias`) VALUES ('DhiMobile');
INSERT INTO `operator` (`alias`) VALUES ('Telecom New Zealand - UMTS Ntework');
INSERT INTO `operator` (`alias`) VALUES ('Empresa Nicaragüense de Telecomunicaciones, S.A. (ENITEL)');
INSERT INTO `operator` (`alias`) VALUES ('Sahel.Com');
INSERT INTO `operator` (`alias`) VALUES ('Econet Wireless Nigeria Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('Hola Paraguay S.A.');
INSERT INTO `operator` (`alias`) VALUES ('Hutchison Telecom S.A.');
INSERT INTO `operator` (`alias`) VALUES ('Compañia Privada de Comunicaciones S.A.');
INSERT INTO `operator` (`alias`) VALUES ('TIM Peru');
INSERT INTO `operator` (`alias`) VALUES ('Islacom');
INSERT INTO `operator` (`alias`) VALUES ('Globe Telecom');
INSERT INTO `operator` (`alias`) VALUES ('Smart Communications');
INSERT INTO `operator` (`alias`) VALUES ('Digitel');
INSERT INTO `operator` (`alias`) VALUES ('Plus GSM (Polkomtel S.A.)');
INSERT INTO `operator` (`alias`) VALUES ('ERA GSM (Polska Telefonia Cyfrowa Sp. Z.o.o.)');
INSERT INTO `operator` (`alias`) VALUES ('Idea (Polska Telefonia Komarkowa Centertel Sp. Z.o.o)');
INSERT INTO `operator` (`alias`) VALUES ('Tele2 Polska (Tele2 Polska Sp. Z.o.o.)');
INSERT INTO `operator` (`alias`) VALUES ('IDEA (UMTS)/PTK Centertel sp. Z.o.o.');
INSERT INTO `operator` (`alias`) VALUES ('Netia Mobile');
INSERT INTO `operator` (`alias`) VALUES ('Premium internet');
INSERT INTO `operator` (`alias`) VALUES ('E-Telko');
INSERT INTO `operator` (`alias`) VALUES ('Telekomunikacja Kolejowa (GSM-R)');
INSERT INTO `operator` (`alias`) VALUES ('Telefony Opalenickie');
INSERT INTO `operator` (`alias`) VALUES ('Optimus - Telecomunicações, S.A.');
INSERT INTO `operator` (`alias`) VALUES ('Oniway - Inforcomunicações, S.A.');
INSERT INTO `operator` (`alias`) VALUES ('TMN - Telecomunicações Movéis Nacionais, S.A.');
INSERT INTO `operator` (`alias`) VALUES ('QATARNET');
INSERT INTO `operator` (`alias`) VALUES ('Vodafone Romania SA');
INSERT INTO `operator` (`alias`) VALUES ('Romtelecom (CDMA)');
INSERT INTO `operator` (`alias`) VALUES ('Cosmorom');
INSERT INTO `operator` (`alias`) VALUES ('Orange Romania');
INSERT INTO `operator` (`alias`) VALUES ('Mobile Comms System');
INSERT INTO `operator` (`alias`) VALUES ('Baykal Westcom');
INSERT INTO `operator` (`alias`) VALUES ('Kuban GSM');
INSERT INTO `operator` (`alias`) VALUES ('New Telephone Company');
INSERT INTO `operator` (`alias`) VALUES ('Ermak RMS');
INSERT INTO `operator` (`alias`) VALUES ('Volgograd Mobile');
INSERT INTO `operator` (`alias`) VALUES ('ECC');
INSERT INTO `operator` (`alias`) VALUES ('Extel');
INSERT INTO `operator` (`alias`) VALUES ('Uralsvyazinform');
INSERT INTO `operator` (`alias`) VALUES ('Stuvtelesot');
INSERT INTO `operator` (`alias`) VALUES ('Telecom XXI');
INSERT INTO `operator` (`alias`) VALUES ('MTN Rwandacell');
INSERT INTO `operator` (`alias`) VALUES ('St. Pierre-et-Miquelon Télécom');
INSERT INTO `operator` (`alias`) VALUES ('Telecom Samoa Cellular Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('GoMobile SamoaTel Ltd');
INSERT INTO `operator` (`alias`) VALUES ('Prima San Marino/San  Marino Telecom');
INSERT INTO `operator` (`alias`) VALUES ('Companhia Santomese de Telecomunicações');
INSERT INTO `operator` (`alias`) VALUES ('Saudi Telecom');
INSERT INTO `operator` (`alias`) VALUES ('Etihad Etisalat Company (Mobily)');
INSERT INTO `operator` (`alias`) VALUES ('Sonatel');
INSERT INTO `operator` (`alias`) VALUES ('Sentel GSM');
INSERT INTO `operator` (`alias`) VALUES ('Expresso Senegal');
INSERT INTO `operator` (`alias`) VALUES ('Telenor d.o.o.');
INSERT INTO `operator` (`alias`) VALUES ('Telekom Srbija a.d.');
INSERT INTO `operator` (`alias`) VALUES ('Vip mobile d.o.o.');
INSERT INTO `operator` (`alias`) VALUES ('Telecom (Seychelles) Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('Lintel (Sierra Leone) Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('Datatel (SL) Ltd GSM');
INSERT INTO `operator` (`alias`) VALUES ('Datatel (SL) Ltd CDMA');
INSERT INTO `operator` (`alias`) VALUES ('SingTel ST GSM900');
INSERT INTO `operator` (`alias`) VALUES ('SingTel ST GSM1800');
INSERT INTO `operator` (`alias`) VALUES ('MobileOne');
INSERT INTO `operator` (`alias`) VALUES ('Starhub');
INSERT INTO `operator` (`alias`) VALUES ('Digital Trunked Radio Network');
INSERT INTO `operator` (`alias`) VALUES ('Orange, GSM');
INSERT INTO `operator` (`alias`) VALUES ('Eurotel, GSM & NMT');
INSERT INTO `operator` (`alias`) VALUES ('Eurotel, UMTS');
INSERT INTO `operator` (`alias`) VALUES ('Orange, UMTS');
INSERT INTO `operator` (`alias`) VALUES ('SI Mobil');
INSERT INTO `operator` (`alias`) VALUES ('T-2 d.o.o.');
INSERT INTO `operator` (`alias`) VALUES ('Tusmobil d.o.o.');
INSERT INTO `operator` (`alias`) VALUES ('Bemobile (Bmobile (SI)) Ltd');
INSERT INTO `operator` (`alias`) VALUES ('Golis Telecommunications Company');
INSERT INTO `operator` (`alias`) VALUES ('Onkod Telecom Ltd');
INSERT INTO `operator` (`alias`) VALUES ('Vodacom (Pty) Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('Telkom SA Ltd');
INSERT INTO `operator` (`alias`) VALUES ('Sentech (Pty) Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('Cell C (Pty) Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('Mobile Telephone Networks (MTN) Pty Ltd');
INSERT INTO `operator` (`alias`) VALUES ('SAPS Gauteng');
INSERT INTO `operator` (`alias`) VALUES ('Neotel Pty Ltd');
INSERT INTO `operator` (`alias`) VALUES ('Cape Town Metropolitan Council');
INSERT INTO `operator` (`alias`) VALUES ('Bokamoso Consortium Pty Ltd');
INSERT INTO `operator` (`alias`) VALUES ('Karabo Telecoms (Pty) Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('Ilizwi Telecommunications Pty Ltd');
INSERT INTO `operator` (`alias`) VALUES ('Thinta Thinta Telecommunications Pty Ltd');
INSERT INTO `operator` (`alias`) VALUES ('Kingdom Communications Pty Ltd');
INSERT INTO `operator` (`alias`) VALUES ('Amatole Telecommunication Pty Ltd');
INSERT INTO `operator` (`alias`) VALUES ('Vodafone España, SAU');
INSERT INTO `operator` (`alias`) VALUES ('France Telecom España, SA');
INSERT INTO `operator` (`alias`) VALUES ('Xfera Móviles, SA');
INSERT INTO `operator` (`alias`) VALUES ('Telefónica Móviles España, SAU');
INSERT INTO `operator` (`alias`) VALUES ('Euskaltel, SA');
INSERT INTO `operator` (`alias`) VALUES ('BT España Compañia de Servicios Globales de');
INSERT INTO `operator` (`alias`) VALUES ('Telecable de Asturias, SAU');
INSERT INTO `operator` (`alias`) VALUES ('R Cable y Telecomunicaciones Galicia, SA');
INSERT INTO `operator` (`alias`) VALUES ('Cableuropa, SAU');
INSERT INTO `operator` (`alias`) VALUES ('E-Plus Móviles, SL');
INSERT INTO `operator` (`alias`) VALUES ('Jazz Telecom, SAU');
INSERT INTO `operator` (`alias`) VALUES ('Best Spain Telecom, SL');
INSERT INTO `operator` (`alias`) VALUES ('Lycamobile, SL');
INSERT INTO `operator` (`alias`) VALUES ('Lleida Networks Serveis Telemàtics, SL');
INSERT INTO `operator` (`alias`) VALUES ('MTN Network Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('Celtel Lanka Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('SD Mobitel');
INSERT INTO `operator` (`alias`) VALUES ('Areeba-Sudan');
INSERT INTO `operator` (`alias`) VALUES ('Network of the World Ltd (NOW)');
INSERT INTO `operator` (`alias`) VALUES ('Zain Sudan');
INSERT INTO `operator` (`alias`) VALUES ('MTN Sudan');
INSERT INTO `operator` (`alias`) VALUES ('Telesur');
INSERT INTO `operator` (`alias`) VALUES ('SPTC');
INSERT INTO `operator` (`alias`) VALUES ('Swazi MTN');
INSERT INTO `operator` (`alias`) VALUES ('Telia Sonera Sverige AB');
INSERT INTO `operator` (`alias`) VALUES ('H3G Access AB');
INSERT INTO `operator` (`alias`) VALUES ('AINMT Sverige AB');
INSERT INTO `operator` (`alias`) VALUES ('3G Infrastructure Services AB');
INSERT INTO `operator` (`alias`) VALUES ('Svenska UMTS-Nät AB');
INSERT INTO `operator` (`alias`) VALUES ('Telenor Sverige AB');
INSERT INTO `operator` (`alias`) VALUES ('Tele2 Sverige AB');
INSERT INTO `operator` (`alias`) VALUES ('Djuice Mobile Sweden, filial till Telenor Mobile Sweden AS');
INSERT INTO `operator` (`alias`) VALUES ('Spring Mobil AB');
INSERT INTO `operator` (`alias`) VALUES ('Linholmen Science Park AB');
INSERT INTO `operator` (`alias`) VALUES ('Barablu Mobile Scandinavia Ltd');
INSERT INTO `operator` (`alias`) VALUES ('Ventelo Sverige AB');
INSERT INTO `operator` (`alias`) VALUES ('TDC Mobil A/S');
INSERT INTO `operator` (`alias`) VALUES ('Wireless Maingate Nordic AB');
INSERT INTO `operator` (`alias`) VALUES ('42IT AB');
INSERT INTO `operator` (`alias`) VALUES ('Generic Mobile Systems Sweden AB');
INSERT INTO `operator` (`alias`) VALUES ('Banverket');
INSERT INTO `operator` (`alias`) VALUES ('EuTel AB');
INSERT INTO `operator` (`alias`) VALUES ('Infobip Ltd');
INSERT INTO `operator` (`alias`) VALUES ('Net4Mobility HB');
INSERT INTO `operator` (`alias`) VALUES ('Digitel Mobile srl');
INSERT INTO `operator` (`alias`) VALUES ('Beepsend AB');
INSERT INTO `operator` (`alias`) VALUES ('MyIndian AB');
INSERT INTO `operator` (`alias`) VALUES ('CoolTEL Aps A.B.');
INSERT INTO `operator` (`alias`) VALUES ('Mercury International Carrier Services');
INSERT INTO `operator` (`alias`) VALUES ('NextGen Mobile Ltd');
INSERT INTO `operator` (`alias`) VALUES ('Mobimax AB');
INSERT INTO `operator` (`alias`) VALUES ('Compatel Ltd');
INSERT INTO `operator` (`alias`) VALUES ('Mobile Arts AB');
INSERT INTO `operator` (`alias`) VALUES ('Tigo Ltd');
INSERT INTO `operator` (`alias`) VALUES ('ReWiCom Scandinavia AB');
INSERT INTO `operator` (`alias`) VALUES ('Swisscom Mobile AG');
INSERT INTO `operator` (`alias`) VALUES ('TDC Switzerland AG');
INSERT INTO `operator` (`alias`) VALUES ('Orange Communications SA');
INSERT INTO `operator` (`alias`) VALUES ('Comfone AG');
INSERT INTO `operator` (`alias`) VALUES ('SBB AG');
INSERT INTO `operator` (`alias`) VALUES ('IN&Phone SA');
INSERT INTO `operator` (`alias`) VALUES ('Tele2 Telecommunications AG');
INSERT INTO `operator` (`alias`) VALUES ('Syriatel');
INSERT INTO `operator` (`alias`) VALUES ('Spacetel Syria');
INSERT INTO `operator` (`alias`) VALUES ('Syrian Telecom');
INSERT INTO `operator` (`alias`) VALUES ('JC Somoncom');
INSERT INTO `operator` (`alias`) VALUES ('CJSC Indigo Tajikistan');
INSERT INTO `operator` (`alias`) VALUES ('TT mobile');
INSERT INTO `operator` (`alias`) VALUES ('Josa Babilon-T');
INSERT INTO `operator` (`alias`) VALUES ('CTJTHSC Tajik-tel');
INSERT INTO `operator` (`alias`) VALUES ('MIC (T) Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('Zantel');
INSERT INTO `operator` (`alias`) VALUES ('Vodacom (T) Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('Celtel (T) Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('AIS GSM');
INSERT INTO `operator` (`alias`) VALUES ('ACT Mobile');
INSERT INTO `operator` (`alias`) VALUES ('T-Mobile');
INSERT INTO `operator` (`alias`) VALUES ('Cosmofon');
INSERT INTO `operator` (`alias`) VALUES ('Nov Operator');
INSERT INTO `operator` (`alias`) VALUES ('WTI Macedonia');
INSERT INTO `operator` (`alias`) VALUES ('Mobik Telekomunikacii dooel');
INSERT INTO `operator` (`alias`) VALUES ('Togo Telecom');
INSERT INTO `operator` (`alias`) VALUES ('Tonga Communications Corporation');
INSERT INTO `operator` (`alias`) VALUES ('Digicel (Tonga) Ltd');
INSERT INTO `operator` (`alias`) VALUES ('TSTT Mobile');
INSERT INTO `operator` (`alias`) VALUES ('Digicel Trinidad and Tobago Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('LaqTel Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('Orascom Telecom');
INSERT INTO `operator` (`alias`) VALUES ('Turkcell');
INSERT INTO `operator` (`alias`) VALUES ('Telsim GSM');
INSERT INTO `operator` (`alias`) VALUES ('Aria');
INSERT INTO `operator` (`alias`) VALUES ('Aycell');
INSERT INTO `operator` (`alias`) VALUES ('Barash Communication Technologies (BCTI)');
INSERT INTO `operator` (`alias`) VALUES ('TM-Cell');
INSERT INTO `operator` (`alias`) VALUES ('IslandCom Communications Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('IslandCom Communication Ltd');
INSERT INTO `operator` (`alias`) VALUES ('Tuvalu Telecommunications Corporation');
INSERT INTO `operator` (`alias`) VALUES ('Celtel Uganda');
INSERT INTO `operator` (`alias`) VALUES ('MTN Uganda Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('Uganda Telecom Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('House of Integrated Technology and Systems Uganda Ltd');
INSERT INTO `operator` (`alias`) VALUES ('Sure Telecom Uganda Ltd');
INSERT INTO `operator` (`alias`) VALUES ('Warid Telecom Uganda Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('Anupam Global Soft Uganda Ltd');
INSERT INTO `operator` (`alias`) VALUES ('i-Tel Ltd');
INSERT INTO `operator` (`alias`) VALUES ('Ukrainian Mobile Communication, UMC');
INSERT INTO `operator` (`alias`) VALUES ('Ukranian Radio Systems, URS');
INSERT INTO `operator` (`alias`) VALUES ('Kyivstar GSM');
INSERT INTO `operator` (`alias`) VALUES ('International Telecommunications Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('Golden Telecom');
INSERT INTO `operator` (`alias`) VALUES ('Astelit');
INSERT INTO `operator` (`alias`) VALUES ('Ukrtelecom');
INSERT INTO `operator` (`alias`) VALUES ('CJSC - Telesystems of Ukraine');
INSERT INTO `operator` (`alias`) VALUES ('Mapesbury Communications Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('O2 UK Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('Jersey Airtel Ltd');
INSERT INTO `operator` (`alias`) VALUES ('FMS Solutions Ltd');
INSERT INTO `operator` (`alias`) VALUES ('Colt Mobile Telecommunications Ltd');
INSERT INTO `operator` (`alias`) VALUES ('Internet Computer Bureau Ltd');
INSERT INTO `operator` (`alias`) VALUES ('Cable and Wireless UK');
INSERT INTO `operator` (`alias`) VALUES ('OnePhone (UK) Ltd');
INSERT INTO `operator` (`alias`) VALUES ('Vodafone Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('Opal Telecom Ltd');
INSERT INTO `operator` (`alias`) VALUES ('Cloud9');
INSERT INTO `operator` (`alias`) VALUES ('Teleware plc');
INSERT INTO `operator` (`alias`) VALUES ('Hutchison 3G UK Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('LogicStar Ltd');
INSERT INTO `operator` (`alias`) VALUES ('Routo Telecommunications Ltd');
INSERT INTO `operator` (`alias`) VALUES ('Vectone Network Ltd');
INSERT INTO `operator` (`alias`) VALUES ('Stour Marine Ltd');
INSERT INTO `operator` (`alias`) VALUES ('Software Cellular Network Ltd');
INSERT INTO `operator` (`alias`) VALUES ('Lycamobile UK Ltd');
INSERT INTO `operator` (`alias`) VALUES ('Teleena UK Ltd');
INSERT INTO `operator` (`alias`) VALUES ('Marathon Telecom Ltd');
INSERT INTO `operator` (`alias`) VALUES ('(aq) Limited T/A aql');
INSERT INTO `operator` (`alias`) VALUES ('Orange');
INSERT INTO `operator` (`alias`) VALUES ('Cable and Wireless Guensey Ltd');
INSERT INTO `operator` (`alias`) VALUES ('Manx Telecom');
INSERT INTO `operator` (`alias`) VALUES ('British Telecom');
INSERT INTO `operator` (`alias`) VALUES ('Airwave mmO2 Ltd');
INSERT INTO `operator` (`alias`) VALUES ('Vodafone Ltd');
INSERT INTO `operator` (`alias`) VALUES ('Hutchison 3G UK Ltd');
INSERT INTO `operator` (`alias`) VALUES ('Network Rail Infrastructure Ltd');
INSERT INTO `operator` (`alias`) VALUES ('Verizon Wireless');
INSERT INTO `operator` (`alias`) VALUES ('Cricket Communications');
INSERT INTO `operator` (`alias`) VALUES ('North Sight Communications Inc');
INSERT INTO `operator` (`alias`) VALUES ('Centennial Communications');
INSERT INTO `operator` (`alias`) VALUES ('ETEX Communications dba ETEX Wireless');
INSERT INTO `operator` (`alias`) VALUES ('MTA Communications dba MTA Wireless');
INSERT INTO `operator` (`alias`) VALUES ('Alaska Communications');
INSERT INTO `operator` (`alias`) VALUES ('Consolidated Telcom');
INSERT INTO `operator` (`alias`) VALUES ('Corr Wireless Communications LLC');
INSERT INTO `operator` (`alias`) VALUES ('Criket Communications LLC');
INSERT INTO `operator` (`alias`) VALUES ('New Mexico RSA 4 East Ltd. Partnership');
INSERT INTO `operator` (`alias`) VALUES ('Pacific Telecom Inc');
INSERT INTO `operator` (`alias`) VALUES ('Sprintcom Inc');
INSERT INTO `operator` (`alias`) VALUES ('Carolina West Wireless');
INSERT INTO `operator` (`alias`) VALUES ('GTA Wireless LLC');
INSERT INTO `operator` (`alias`) VALUES ('T-Mobile USA');
INSERT INTO `operator` (`alias`) VALUES ('Alaska Wireless Communications LLC');
INSERT INTO `operator` (`alias`) VALUES ('Contennial Puerto Rio License Corp.');
INSERT INTO `operator` (`alias`) VALUES ('Blanca Telephone Company');
INSERT INTO `operator` (`alias`) VALUES ('Smith Bagley Inc, dba Cellular One');
INSERT INTO `operator` (`alias`) VALUES ('High Plains Midwest LLC, dba Wetlink Communications');
INSERT INTO `operator` (`alias`) VALUES ('Mohave Cellular L.P.');
INSERT INTO `operator` (`alias`) VALUES ('Cellular Network Partnership dba Pioneer Cellular');
INSERT INTO `operator` (`alias`) VALUES ('Guamcell Cellular and Paging');
INSERT INTO `operator` (`alias`) VALUES ('New Cingular Wireless PCS, LLC');
INSERT INTO `operator` (`alias`) VALUES ('TX-11 Acquistion LLC');
INSERT INTO `operator` (`alias`) VALUES ('Wave Runner LLC');
INSERT INTO `operator` (`alias`) VALUES ('Cincinnati Bell Wireless LLC');
INSERT INTO `operator` (`alias`) VALUES ('Alaska Digitel LLC');
INSERT INTO `operator` (`alias`) VALUES ('Numerex Corp');
INSERT INTO `operator` (`alias`) VALUES ('North East Cellular Inc.');
INSERT INTO `operator` (`alias`) VALUES ('TMP Corporation');
INSERT INTO `operator` (`alias`) VALUES ('nTELOS Communications Inc (Virginia PCS Alliance LC)');
INSERT INTO `operator` (`alias`) VALUES ('Choice Phone LLC');
INSERT INTO `operator` (`alias`) VALUES ('Public Service Cellular, Inc.');
INSERT INTO `operator` (`alias`) VALUES ('Nsighttel Wireless LLC');
INSERT INTO `operator` (`alias`) VALUES ('Transactions Network Services');
INSERT INTO `operator` (`alias`) VALUES ('Iowa Wireless Services LLC');
INSERT INTO `operator` (`alias`) VALUES ('Wireless Solutions International');
INSERT INTO `operator` (`alias`) VALUES ('MTPCS LLC');
INSERT INTO `operator` (`alias`) VALUES ('Inland Cellular Telephone Company');
INSERT INTO `operator` (`alias`) VALUES ('New Cell Inc. dba Cellcom');
INSERT INTO `operator` (`alias`) VALUES ('Elkhart Telephone Co. Inc. dba Epic Touch Co.');
INSERT INTO `operator` (`alias`) VALUES ('Agri-Valley Broadband Inc');
INSERT INTO `operator` (`alias`) VALUES ('Airadigm Communications');
INSERT INTO `operator` (`alias`) VALUES ('Jasper Wireless Inc.');
INSERT INTO `operator` (`alias`) VALUES ('AT&T Mobility Vanguard Services');
INSERT INTO `operator` (`alias`) VALUES ('Keystane Wireless LLC');
INSERT INTO `operator` (`alias`) VALUES ('Cross Valiant Cellular Partnership');
INSERT INTO `operator` (`alias`) VALUES ('Wireless Solutions International Inc.');
INSERT INTO `operator` (`alias`) VALUES ('US Cellular');
INSERT INTO `operator` (`alias`) VALUES ('Convey Communications Inc');
INSERT INTO `operator` (`alias`) VALUES ('East Kentucky Network LLC dba Appalachian Wireless');
INSERT INTO `operator` (`alias`) VALUES ('Lynch 3G Communications Corporation');
INSERT INTO `operator` (`alias`) VALUES ('Iowa Wireless Services LLC dba I Wireless');
INSERT INTO `operator` (`alias`) VALUES ('Connect Net Inc');
INSERT INTO `operator` (`alias`) VALUES ('PinPoint Communications Inc.');
INSERT INTO `operator` (`alias`) VALUES ('LCFR LLC');
INSERT INTO `operator` (`alias`) VALUES ('South Canaan Cellular Communications Co. LP');
INSERT INTO `operator` (`alias`) VALUES ('Caprock Cellular Ltd. Partnership');
INSERT INTO `operator` (`alias`) VALUES ('Telecom North America Mobile Inc');
INSERT INTO `operator` (`alias`) VALUES ('Aeris Communications, Inc.');
INSERT INTO `operator` (`alias`) VALUES ('TX RSA 15B2, LP dba Five Star Wireless');
INSERT INTO `operator` (`alias`) VALUES ('Kaplan Telephone Company Inc.');
INSERT INTO `operator` (`alias`) VALUES ('Advantage Cellular Systems, Inc.');
INSERT INTO `operator` (`alias`) VALUES ('Rural Cellular Corporation');
INSERT INTO `operator` (`alias`) VALUES ('Cable & Communications Corporation dba Mid-Rivers Wireless');
INSERT INTO `operator` (`alias`) VALUES ('James Valley Wireless LLC');
INSERT INTO `operator` (`alias`) VALUES ('Copper Valley Wireless');
INSERT INTO `operator` (`alias`) VALUES ('Iris Wireless LLC');
INSERT INTO `operator` (`alias`) VALUES ('Texas RSA 1 dba XIT Wireless');
INSERT INTO `operator` (`alias`) VALUES ('UBET Wireless');
INSERT INTO `operator` (`alias`) VALUES ('Globalstar USA');
INSERT INTO `operator` (`alias`) VALUES ('Texas RSA 7B3 dba Peoples Wireless Services');
INSERT INTO `operator` (`alias`) VALUES ('Worldcall Interconnect');
INSERT INTO `operator` (`alias`) VALUES ('Chariton Valley Communications Corp., Inc.');
INSERT INTO `operator` (`alias`) VALUES ('Missouri RSA No. 5 Partnership');
INSERT INTO `operator` (`alias`) VALUES ('Indigo Wireless, Inc.');
INSERT INTO `operator` (`alias`) VALUES ('Commnet Wireless, LLC');
INSERT INTO `operator` (`alias`) VALUES ('Thumb Cellular Limited Partnership');
INSERT INTO `operator` (`alias`) VALUES ('Space Data Corporation');
INSERT INTO `operator` (`alias`) VALUES ('Wisconsin RSA#7 Ltd Patnership');
INSERT INTO `operator` (`alias`) VALUES ('Pine Telephone Company dba Pine Cellular');
INSERT INTO `operator` (`alias`) VALUES ('LightSquared LP');
INSERT INTO `operator` (`alias`) VALUES ('Cross Telephone Company');
INSERT INTO `operator` (`alias`) VALUES ('Wilkes Cellular Inc.');
INSERT INTO `operator` (`alias`) VALUES ('PetroCom LLC');
INSERT INTO `operator` (`alias`) VALUES ('Cingular Wireless, Licensee Pacific Telesis Mobile Services, LLC');
INSERT INTO `operator` (`alias`) VALUES ('Cellular Properties Inc.');
INSERT INTO `operator` (`alias`) VALUES ('ARINC');
INSERT INTO `operator` (`alias`) VALUES ('Emery-Telecom Wireless Inc');
INSERT INTO `operator` (`alias`) VALUES ('United States Cellular');
INSERT INTO `operator` (`alias`) VALUES ('Cellular South Inc');
INSERT INTO `operator` (`alias`) VALUES ('Cordova Wireless Communications Inc');
INSERT INTO `operator` (`alias`) VALUES ('SLO Cellular Inc. dba CellularOne of San Luis Obispo');
INSERT INTO `operator` (`alias`) VALUES ('Pinpoint Wireless Inc.');
INSERT INTO `operator` (`alias`) VALUES ('Nexus Communications Inc');
INSERT INTO `operator` (`alias`) VALUES ('Leaco Rural Telephone Company Inc');
INSERT INTO `operator` (`alias`) VALUES ('Commnet Wireless LLC');
INSERT INTO `operator` (`alias`) VALUES ('Bug Tussel Wireless LLC');
INSERT INTO `operator` (`alias`) VALUES ('Illinois Valley Cellular');
INSERT INTO `operator` (`alias`) VALUES ('Sagebrush Cellular Inc dba Nemont');
INSERT INTO `operator` (`alias`) VALUES ('Stelera Wireless LLC');
INSERT INTO `operator` (`alias`) VALUES ('GCI Communications Corp.');
INSERT INTO `operator` (`alias`) VALUES ('Iowa RSA No.2 Ltd Partnership');
INSERT INTO `operator` (`alias`) VALUES ('Northwest Missouri Cellular Limited Partnership');
INSERT INTO `operator` (`alias`) VALUES ('RSA 1 Limited Partnership dba Cellular 29 Plus');
INSERT INTO `operator` (`alias`) VALUES ('Bluegrass Cellular LLC');
INSERT INTO `operator` (`alias`) VALUES ('Panhandle Telecommunication Systems Inc.');
INSERT INTO `operator` (`alias`) VALUES ('Fisher Wireless Services Inc');
INSERT INTO `operator` (`alias`) VALUES ('Vitelcom Cellular Inc dba Innovative Wireless');
INSERT INTO `operator` (`alias`) VALUES ('Sprintcom');
INSERT INTO `operator` (`alias`) VALUES ('CTC Telecom Inc');
INSERT INTO `operator` (`alias`) VALUES ('Wireless Communications Venture');
INSERT INTO `operator` (`alias`) VALUES ('Proximiti Mobility Inc');
INSERT INTO `operator` (`alias`) VALUES ('Commnet Midwest LLC');
INSERT INTO `operator` (`alias`) VALUES ('OTZ Communications Inc');
INSERT INTO `operator` (`alias`) VALUES ('Bend Cable Communications LLC');
INSERT INTO `operator` (`alias`) VALUES ('California RSA No3 Ltd Partnership dba Golden State Cellular');
INSERT INTO `operator` (`alias`) VALUES ('Cox TMI Wireless LLC');
INSERT INTO `operator` (`alias`) VALUES ('North Dakota Network Co.');
INSERT INTO `operator` (`alias`) VALUES ('Terrestar Networks Inc');
INSERT INTO `operator` (`alias`) VALUES ('Corr Wireless Communications');
INSERT INTO `operator` (`alias`) VALUES ('Standing Rock Telecommunications');
INSERT INTO `operator` (`alias`) VALUES ('United Wireless Inc');
INSERT INTO `operator` (`alias`) VALUES ('Metro PCS Wireless Inc');
INSERT INTO `operator` (`alias`) VALUES ('Pine Belt Cellular Inc dba Pine Belt Wireless');
INSERT INTO `operator` (`alias`) VALUES ('GreenFly LLC');
INSERT INTO `operator` (`alias`) VALUES ('TeleBeeper of New Mexico Inc');
INSERT INTO `operator` (`alias`) VALUES ('TotalSolutions Telecom LLC');
INSERT INTO `operator` (`alias`) VALUES ('Northeast Wireless Networks LLC');
INSERT INTO `operator` (`alias`) VALUES ('Maine PCS LLC');
INSERT INTO `operator` (`alias`) VALUES ('Telalaska Cellular');
INSERT INTO `operator` (`alias`) VALUES ('NetAmerica Alliance LLC');
INSERT INTO `operator` (`alias`) VALUES ('Edigen Inc');
INSERT INTO `operator` (`alias`) VALUES ('Geneseo Communications Services Inc');
INSERT INTO `operator` (`alias`) VALUES ('Thumb Cellular LLC');
INSERT INTO `operator` (`alias`) VALUES ('Nsight Spectrum LLC');
INSERT INTO `operator` (`alias`) VALUES ('Uintah Basin Electronic Telecommunications');
INSERT INTO `operator` (`alias`) VALUES ('Globecomm Network Services Corporation');
INSERT INTO `operator` (`alias`) VALUES ('Gigsky Inc');
INSERT INTO `operator` (`alias`) VALUES ('Sl Wireless LLC');
INSERT INTO `operator` (`alias`) VALUES ('Missouri RSA No 5 Partnership dba Chariton Valley Wireless');
INSERT INTO `operator` (`alias`) VALUES ('Cablevision Systems Corporation');
INSERT INTO `operator` (`alias`) VALUES ('Nextel Communications Inc');
INSERT INTO `operator` (`alias`) VALUES ('Ancel');
INSERT INTO `operator` (`alias`) VALUES ('CTI Móvil');
INSERT INTO `operator` (`alias`) VALUES ('Buztel');
INSERT INTO `operator` (`alias`) VALUES ('Uzmacom');
INSERT INTO `operator` (`alias`) VALUES ('Daewoo Unitel');
INSERT INTO `operator` (`alias`) VALUES ('Coscom');
INSERT INTO `operator` (`alias`) VALUES ('Uzdunrobita');
INSERT INTO `operator` (`alias`) VALUES ('SMILE');
INSERT INTO `operator` (`alias`) VALUES ('Digicel Vanuatu');
INSERT INTO `operator` (`alias`) VALUES ('Infonet');
INSERT INTO `operator` (`alias`) VALUES ('Corporación Digitel');
INSERT INTO `operator` (`alias`) VALUES ('Telcel, C.A.');
INSERT INTO `operator` (`alias`) VALUES ('Telecomunicaciones Movilnet, C.A.');
INSERT INTO `operator` (`alias`) VALUES ('Mobifone');
INSERT INTO `operator` (`alias`) VALUES ('Vinaphone');
INSERT INTO `operator` (`alias`) VALUES ('EVNTelecom');
INSERT INTO `operator` (`alias`) VALUES ('Beeline VN/GTEL Mobile JSC');
INSERT INTO `operator` (`alias`) VALUES ('EVNTelecom/ 3G');
INSERT INTO `operator` (`alias`) VALUES ('Celtel Zambia Ltd.');
INSERT INTO `operator` (`alias`) VALUES ('Net One');
INSERT INTO `operator` (`alias`) VALUES ('Wi-Fi');
INSERT INTO `operator` (`alias`) VALUES ('Telefónica Móviles Perú');
INSERT INTO `operator` (`alias`) VALUES ('Movistar México (Movistar INTERNET)');
INSERT INTO `operator` (`alias`) VALUES ('LG Telecom');
INSERT INTO `operator` (`alias`) VALUES ('Asia Pacific Telecom Co. Ltd (APT)');
INSERT INTO `operator` (`alias`) VALUES ('VMAX Telecom Co. Ltd');
INSERT INTO `operator` (`alias`) VALUES ('Global Mobile Corp.');
INSERT INTO `operator` (`alias`) VALUES ('ACeS Taiwan - ACeS Taiwan Telecommunications Co Ltd');
INSERT INTO `operator` (`alias`) VALUES ('KG Telecom');
INSERT INTO `operator` (`alias`) VALUES ('VIBO');
INSERT INTO `operator` (`alias`) VALUES ('Mobitai');
INSERT INTO `operator` (`alias`) VALUES ('Taiwan Cellular');
INSERT INTO `operator` (`alias`) VALUES ('TransAsia');
INSERT INTO `operator` (`alias`) VALUES ('IUSACell/UneFon');
INSERT INTO `operator` (`alias`) VALUES ('Axtel');
INSERT INTO `operator` (`alias`) VALUES ('SAI PCS');
INSERT INTO `operator` (`alias`) VALUES ('Operadora Unefon SA de CV');
INSERT INTO `operator` (`alias`) VALUES ('Dacom');
INSERT INTO `operator` (`alias`) VALUES ('Telefonica Móviles Argentina SA');
INSERT INTO `operator` (`alias`) VALUES ('Nll Holdings');
INSERT INTO `operator` (`alias`) VALUES ('Hutchison Telecommunications Argentina S.A');
INSERT INTO `operator` (`alias`) VALUES ('TE.SA.M Argentina S.A');
INSERT INTO `operator` (`alias`) VALUES ('Telefonica Celular Del Paraguay S.A. (Telecel)');
INSERT INTO `operator` (`alias`) VALUES ('Airtel/Warid');
INSERT INTO `operator` (`alias`) VALUES ('TeleTalk');
