INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('103.2.28114','Line','JP','AS','Line Corporation');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('103.2.28115','Line','JP','AS','Line Corporation');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('103.2.28116','Line','JP','AS','Line Corporation');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('103.2.28117','Line','JP','AS','Line Corporation');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('103.2.28118','Line','JP','AS','Line Corporation');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('103.2.28119','Line','JP','AS','Line Corporation');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('103.2.28120','Line','JP','AS','Line Corporation');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('103.2.28121','Line','JP','AS','Line Corporation');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('103.2.2867','Line','JP','AS','Line Corporation');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('103.2.2868','Line','JP','AS','Line Corporation');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('103.2.3140','Line','JP','AS','Line Corporation');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('103.2.3141','Line','JP','AS','Line Corporation');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('103.2.3142','Line','JP','AS','Line Corporation');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('103.2.3143','Line','JP','AS','Line Corporation');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('103.2.3144','Line','JP','AS','Line Corporation');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('103.2.3145','Line','JP','AS','Line Corporation');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('103.2.3146','Line','JP','AS','Line Corporation');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('103.2.3147','Line','JP','AS','Line Corporation');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('116.51.221','Telegram','SG','AS','NTT Singapore Pte Lt');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('119.235.224165','Line','JP','AS','Line Corporation');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('119.235.236217','Line','JP','AS','Line Corporation');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('119.235.236218','Line','JP','AS','Line Corporation');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('119.235.236219','Line','JP','AS','Line Corporation');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('119.235.236220','Line','JP','AS','Line Corporation');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('119.235.236221','Line','JP','AS','Line Corporation');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('119.235.236222','Line','JP','AS','Line Corporation');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('149.154.167117','Telegram','GB','EU','Telegram Messenger L');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('149.154.167118','Telegram','GB','EU','Telegram Messenger L');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('149.154.167119','Telegram','GB','EU','Telegram Messenger L');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('149.154.167120','Telegram','GB','EU','Telegram Messenger L');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('149.154.16743','Telegram','GB','EU','Telegram Messenger L');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('149.154.16745','Telegram','GB','EU','Telegram Messenger L');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('149.154.16754','Telegram','GB','EU','Telegram Messenger L');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('149.154.16755','Telegram','GB','EU','Telegram Messenger L');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('149.154.16756','Telegram','GB','EU','Telegram Messenger L');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('149.154.16757','Telegram','GB','EU','Telegram Messenger L');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('149.154.17119','Telegram','GB','EU','Telegram Messenger L');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('149.154.17515','Telegram','GB','EU','RIPE Network Coordin');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('172.16.0225','Sonda E2E_1','ES','EU','Telefonica Investiga');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('172.16.0226','Sonda E2E_2','ES','EU','Telefonica Investiga');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('172.16.232193','Sonda E2E_1','ES','EU','Telefonica Investiga');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('172.16.232194','Sonda E2E_1','ES','EU','Telefonica Investiga');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('173.240.511','Telegram','US','NA','CentriLogic');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('173.240.5252','Telegram','US','NA','CentriLogic');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('174.140.1425','Telegram','US','NA','Carpathia Hosting');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('181.131.1958','Dev-Kuryaki','CO','AS','EPM Telecomunicacion');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('186.85.72228','Dev-Kuryaki','CO','SA','Telmex Colombia');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('203.104.1382','Line','JP','AS','Line Corporation');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('203.104.1383','Line','JP','AS','Line Corporation');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('203.104.1384','Line','JP','AS','Line Corporation');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('203.104.1385','Line','JP','AS','Line Corporation');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('203.104.1386','Line','JP','AS','Line Corporation');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('203.104.1387','Line','JP','AS','Line Corporation');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('203.104.1388','Line','JP','AS','Line Corporation');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('203.104.1389','Line','JP','AS','Line Corporation');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('203.104.14014','Line','JP','AS','Line Corporation');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('31.210.23511','Telegram','GB','EU','Crosspoint Colocatio');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('54.69.16620','FxOS Hello','EU','NA','Amazon');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('54.69.25165','FxOS Hello','EU','NA','Amazon');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('54.76.48197','FxOS Hello','EU','NA','Amazon');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('149.154.175.114','Telegram','GB','EU','Telegram Messenger L');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('149.154.175.16','Telegram','GB','EU','Telegram Messenger L');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('203.104.140.111','Line','JP','AS','Line Corporation');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('203.104.140.90','Line','JP','AS','Line Corporation');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('203.104.140.86','Line','JP','AS','Line Corporation');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('203.104.140.93','Line','JP','AS','Line Corporation');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('203.104.140.107','Line','JP','AS','Line Corporation');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('203.104.140.102','Line','JP','AS','Line Corporation');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('203.104.140.92','Line','JP','AS','Line Corporation');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('203.104.140.108','Line','JP','AS','Line Corporation');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('203.104.140.98','Line','JP','AS','Line Corporation'); 
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('203.104.140.88','Line','JP','AS','Line Corporation');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('203.104.140.103','Line','JP','AS','Line Corporation');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('203.104.140.100','Line','JP','AS','Line Corporation'); 
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('203.104.140.104','Line','JP','AS','Line Corporation');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('203.104.140.96','Line','JP','AS','Line Corporation');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('203.104.140.105','Line','JP','AS','Line Corporation'); 
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('203.104.140.88','Line','JP','AS','Line Corporation');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('203.104.140.103','Line','JP','AS','Line Corporation');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('203.104.140.100','Line','JP','AS','Line Corporation'); 
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('203.104.140.87','Line','JP','AS','Line Corporation');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('203.104.140.101','Line','JP','AS','Line Corporation');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('203.104.140.89','Line','JP','AS','Line Corporation'); 
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('203.104.140.110','Line','JP','AS','Line Corporation');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('203.104.140.91','Line','JP','AS','Line Corporation');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('203.104.140.97','Line','JP','AS','Line Corporation'); 
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('203.104.140.94','Line','JP','AS','Line Corporation');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('203.104.140.106','Line','JP','AS','Line Corporation');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('203.104.140.109','Line','JP','AS','Line Corporation'); 
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('203.104.140.85','Line','JP','AS','Line Corporation');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('203.104.140.84','Line','JP','AS','Line Corporation');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('203.104.140.99','Line','JP','AS','Line Corporation');
INSERT INTO `alias_ip_servidores_aplicaciones` (`ip`,`alias`,`country`,`continent`, `isp`) VALUES ('203.104.140.95','Line','JP','AS','Line Corporation'); 



